import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading, isError } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (isError) return <div>Bumped into some errors...</div>;

  if (!data) return <div>Something went wrong...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            <h1 className="text-6xl font-bold text-white">
              User is {!!user.isSignedIn ? "Logged In" : "Not Logged In"}
            </h1>
          </div>
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <div className="">
            {data?.map((p) => (
              <div key={p.id} className="border-b border-slate-400 p-8">
                {p.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
